apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u1sj1edoi-python
  janus-idp.io/tekton: u1sj1edoi-python
  backstage.io/kubernetes-id: u1sj1edoi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u1sj1edoi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
